service: docker-example-springboot
package:
  individually: true
  artifact: build/libs/function.jar
provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  runtime: java17

functions:
  api:
    timeout: 900
    handler: com.example.demo.LambdaHandler
    snapStart: true
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MAIN_CLASS: com.example.demo.DemoApplicationKt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  scriptable:
    hooks:
      "before:package:createDeploymentArtifacts": >
        docker run --rm
        -v %cd%:/app
        -w /app
        gradle:jdk17
        gradle lambdaJar

plugins:
  - serverless-scriptable-plugin
